version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    sschedule:
      interval: "weekly"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/web/inc"
    schedule:
      interval: "weekly"

  # Quick install App
  - package-ecosystem: "composer"
    directory: "/web/src/"
    schedule:
      interval: "weekly"
