---
kind: pipeline
type: ssh
name: HestiaCP + Nginx + Apache2  

concurrency:
  limit: 1

server:
  host:
    from_secret: server_address
  user: 
    from_secret: username
  ssh_key: 
    from_secret: ssh_key

platform:
  os: linux
  arch: amd64
   
steps:
- name: Down submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: build-install
  commands:
  - ./src/hst_autocompile.sh --hestia --install '~localsrc'
- name: Run Bats
  commands:
  - bats ./test/test.bats
- name: Run Check PHP
  commands: 
  - ./test/check_php.sh

trigger:
  event: [ push, pull_request ]

---
kind: pipeline
type: ssh
name: HestiaCP + Nginx  

concurrency:
  limit: 1

server:
  host:
    from_secret: server_address2
  user: 
    from_secret: username
  ssh_key: 
    from_secret: ssh_key

platform:
  os: linux
  arch: amd64
   
steps:
- name: Down submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: build-install
  commands:
  - ./src/hst_autocompile.sh --hestia --install '~localsrc'
- name: Run Bats
  commands:
  - bats ./test/test.bats
- name: Run Check PHP
  commands: 
  - ./test/check_php.sh

trigger:
  event: [ push, pull_request ]

---
kind: signature
hmac: 206d86147c4ee57339c4af654f073c0d2f136f591c890eb4244ccaef087c433f