name: Crowdin

on:
  workflow_dispatch:

jobs:
  update-pot:
    name: Update .pot file
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        if: github.repository == 'hestiacp/hestiacp'
      - name: crowdin action
        uses: crowdin/github-action@6a189cf93a647dc1f4214eb10447661de26b577a # v1
        if: github.repository == 'hestiacp/hestiacp'
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
